### ISSUE TITLE
前辈你好，麻烦问下笔记的md文件能提供吗？

### ISSUE THREAD

**Issue by pityk3369** [LooperXX/CS224n-Reading-Notes#3]

**Comment by LooperXX** [comment]
您好，个人不打算对 Markdown 文件进行开源，但已经逐步搬运到知乎平台 https://zhuanlan.zhihu.com/xuxiao-NLP 您可以在这一专栏找到每个 pdf 的对应文章，您有需要的话可以直接复制知乎文章内容即可解决您的问题。
