### ISSUE TITLE
issue about CS224n-2019-01-Introduction and Word Vectors.pdf

### ISSUE THREAD

**Issue by XianWang521** [LooperXX/CS224n-Reading-Notes#4]
word2vec objective function部分，“在大小为m..., 给定中心词wj”应该是“中心词wt”吧

**Comment by LooperXX** [comment]
嗨~
感谢你细致的阅读并纠正，这里确实应该纠正为中心词 wt，当时没有注意到原Slides上这里写错了~
再次感谢~
