### ISSUE TITLE
typo in lecture 02 word vectors and word senses

### ISSUE THREAD

**Issue by eleveyuan** [LooperXX/CS224n-Reading-Notes#5]
在 but why not capture co-occurrence counts directly?这一节里面
![image](https://user-images.githubusercontent.com/85916131/170807090-695f94a6-18e9-4cea-b90d-85f697e9224d.png)
这里应该是pearson相关系数？皮尔逊相关系数？

**Comment by LooperXX** [comment]
感谢指正！
